import type { Product } from "@/types"

export const products: Product[] = [
  {
    id: "1",
    name: "Wireless Bluetooth Headphones",
    description:
      "Premium quality wireless headphones with noise cancellation and 30-hour battery life. Perfect for music lovers.",
    price: 15999,
    originalPrice: 19999,
    discount: 20,
    image: "/placeholder.svg?height=300&width=300",
    category: "electronics",
    rating: 4.5,
    reviews: 128,
    stock: 15,
    featured: true,
    tags: ["wireless", "bluetooth", "headphones", "audio"],
  },
  {
    id: "2",
    name: "Smart Fitness Watch",
    description: "Track your health and fitness with this advanced smartwatch featuring GPS and heart rate monitoring.",
    price: 24999,
    image: "/placeholder.svg?height=300&width=300",
    category: "electronics",
    rating: 4.3,
    reviews: 89,
    stock: 8,
    featured: true,
    tags: ["smartwatch", "fitness", "health", "gps"],
  },
  {
    id: "3",
    name: "Cotton Kurta for Men",
    description:
      "Comfortable and traditional cotton kurta available in multiple colors. Perfect for festivals and casual wear.",
    price: 2499,
    image: "/placeholder.svg?height=300&width=300",
    category: "clothing",
    rating: 4.7,
    reviews: 203,
    stock: 25,
    featured: false,
    tags: ["kurta", "cotton", "traditional", "casual"],
  },
  {
    id: "4",
    name: "Professional DSLR Camera",
    description:
      "24MP DSLR camera perfect for professional photography with beautiful image quality and multiple lenses support.",
    price: 89999,
    image: "/placeholder.svg?height=300&width=300",
    category: "electronics",
    rating: 4.8,
    reviews: 45,
    stock: 3,
    featured: true,
    tags: ["camera", "dslr", "photography", "professional"],
  },
  {
    id: "5",
    name: "Ergonomic Study Chair",
    description:
      "Comfortable ergonomic study chair with lumbar support and adjustable height. Perfect for students and professionals.",
    price: 12999,
    originalPrice: 15999,
    discount: 19,
    image: "/placeholder.svg?height=300&width=300",
    category: "home",
    rating: 4.4,
    reviews: 167,
    stock: 12,
    featured: true,
    tags: ["chair", "study", "ergonomic", "furniture"],
  },
  {
    id: "6",
    name: "Yoga Mat Premium",
    description:
      "Non-slip premium yoga mat made from eco-friendly materials, perfect for all yoga practices and meditation.",
    price: 3999,
    image: "/placeholder.svg?height=300&width=300",
    category: "sports",
    rating: 4.6,
    reviews: 312,
    stock: 20,
    featured: false,
    tags: ["yoga", "fitness", "eco-friendly", "exercise"],
  },
  {
    id: "7",
    name: "Stainless Steel Water Bottle",
    description: "Insulated stainless steel water bottle that keeps drinks cold for 24 hours or hot for 12 hours.",
    price: 1999,
    image: "/placeholder.svg?height=300&width=300",
    category: "sports",
    rating: 4.5,
    reviews: 89,
    stock: 30,
    featured: true,
    tags: ["water bottle", "insulated", "stainless steel", "hydration"],
  },
  {
    id: "8",
    name: "Designer Sunglasses",
    description: "Stylish designer sunglasses with UV protection and polarized lenses. Perfect for Indian summers.",
    price: 7999,
    originalPrice: 9999,
    discount: 20,
    image: "/placeholder.svg?height=300&width=300",
    category: "clothing",
    rating: 4.2,
    reviews: 76,
    stock: 18,
    featured: true,
    tags: ["sunglasses", "designer", "uv protection", "fashion"],
  },
  {
    id: "9",
    name: "Smart Home Speaker",
    description:
      "Voice-controlled smart speaker with premium sound quality and smart home integration. Supports Hindi and Tamil commands.",
    price: 8999,
    image: "/placeholder.svg?height=300&width=300",
    category: "electronics",
    rating: 4.4,
    reviews: 234,
    stock: 22,
    featured: false,
    tags: ["smart home", "speaker", "voice control", "audio"],
  },
  {
    id: "10",
    name: "Ceramic Plant Pot Set",
    description:
      "Beautiful set of 3 ceramic plant pots with drainage holes, perfect for indoor plants and home decoration.",
    price: 2999,
    image: "/placeholder.svg?height=300&width=300",
    category: "home",
    rating: 4.7,
    reviews: 145,
    stock: 16,
    featured: false,
    tags: ["plant pots", "ceramic", "home decor", "gardening"],
  },
]
